//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuyenMai()
        {
            this.SanPhams = new HashSet<SanPham>();
        }

        [Display(Name = "Khuyến mãi")]
        public int MaKM { get; set; }
        [Display(Name = "Tên khuyến mãi")]
        public string TenKM { get; set; }
        [Display(Name = "Tỉ lệ giảm")]
        public Nullable<double> TiLeKM { get; set; }
        [Display(Name = "Từ ngày")]
        public Nullable<System.DateTime> NgayBD { get; set; }
        [Display(Name = "Đến ngày")]
        public Nullable<System.DateTime> NgayKT { get; set; }
        [Display(Name = "Hình")]
        public string pr_img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
