//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTHDs = new HashSet<CTHD>();
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int MaSP { get; set; }
        [Display(Name = "Tên SP")]
        public string TenSP { get; set; }
        [Display(Name = "Đơn giá")]
        public int GiaSP { get; set; }
        [Display(Name = "Mô tả")]
        public string MotaSP { get; set; }
        [Display(Name = "Ảnh")]
        public string img { get; set; }
        [Display(Name = "Sao")]
        public double Sao { get; set; }
        [Display(Name = "Số đánh giá")]
        public int SoLuotDanhGia { get; set; }
        [Display(Name = "Số lượng")]
        public int SoluongSP { get; set; }
        [Display(Name = "Loại SP")]
        public Nullable<int> maLoai { get; set; }
        [Display(Name = "Khuyến mãi")]
        public Nullable<int> MaKM { get; set; }
        [Display(Name = "Tình trạng")]
        public Nullable<int> tinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
